policy:
  - section:
      - id: ['type']
        block-list: ['other']
        label:
          - name: bug 🐛
            keys: ['Bug Report']

          - name: RFE 🎁
            keys: ['Feature Request']
